### ISSUE TITLE
Enable translation of interface

### ISSUE THREAD

**Issue by walker** [jlanio/Geogig-Desktop#2]
The app should support translation of interface using angular-translate.

**Comment by jlanio** [comment]
currently working: https://github.com/jlanio/Geogig-Desktop/commit/12b2372751100619f2b38bd418f64dd9f0815d65

**Comment by jlanio** [comment]
In order to organize the development I will merge #4  the functions_to_POO branch. And for all development activities we must create new  branch **Dev**. Similar to what geogig does:

We maintain two branches:

> dev - this is where live development happens, we ask that incoming pull requests be made against this branch
master - this represents the latest stable release

And add CONTRIBUTING.md with the rules described. what do you think? Suggestions?! @walker

**Comment by jlanio** [comment]
I'm working on refactoring lib and geogig controllers (functions_to_POO branch) in order to facilitate the potential aggregation of new commiters.

**Comment by walker** [comment]
> I'm working on refactoring lib and geogig controllers (functions_to_POO branch) in order to facilitate the potential aggregation of new commiters.

This would be great.

> - [] And add CONTRIBUTING.md with the rules described.
> - [] merge #4 the functions_to_POO branch.
> - [] Create new branch Dev.
> what do you think? Suggestions?! @walker

I would just dump PR #4. It ain't worth it. I'll pull an updated dev and re-try my further attempts at translation.

**Comment by jlanio** [comment]
> I would just dump PR #4. It ain't worth it. I'll pull an updated dev and re-try my further attempts at translation.

@walker  branch Dev created. 
_branch Dev in WIP._

**Comment by jlanio** [comment]
I believe we can close this question.
Partially added translation.
Please clone `dev `branch.

check:
91ad8113e797d45ec200835c98d21cb432ebfd07 and c32f88b0f67abd5c1d7ef40c493f9e15c691d4aa

Close issue?
