### ISSUE TITLE
Why I could not work on the branches and tags v0.9?

### ISSUE THREAD

**Issue by xqx930807** [jlanio/Geogig-Desktop#5]
That's a good project. So I test on the branch master and dev.
So I installed Node.js 6.10 and run 'npm install ' & 'npm start'.
But Both two branches cannot render the window correctly.

finally, I checkout the tag v0.9.
The window could render correctly,
but when I try to add the remote geogig repos, the "+New" button could not reponse..

emmm. BTW,the exe file in the release page works fine. 
So , is there any ways to run  on the sources of tag v0.9?

**Comment by jlanio** [comment]
Hello @xqx930807 , thank you for your interest in the project.

Apparently some dependencies are omitted when raising brach dev with node npm install.

I'll make the correction and then let you know

**Comment by jlanio** [comment]
_UPDATE_\
last [commit](https://github.com/jlanio/Geogig-Desktop/blob/dev/CONTRIBUTING.md) Contains the information to up application. 

In every way:

Building
---------

To build Geogig-Desktop from source, follow these steps.\
  Note: To clone and run this repository you'll need [Git](https://git-scm.com) and [Node.js](https://nodejs.org/en/download/) (which comes with [npm](http://npmjs.com)) installed on your computer. From your command line:

- Clone the GeoGig source code repository.

	`$git clone https://github.com/jlanio/Geogig-Desktop.git`\
  We encourage branch **dev**:\
  `$git checkout  -b origin/dev`
## To Use After cloning

```bash
# Go into the repository
cd Geogig-Desktop
# Install dependencies
npm install
# Setting environment (downloa geogig command line)
node postinstall.js
# Run the app
npm start
```

**Comment by xqx930807** [comment]
OK.I am testing.
If I have installed Geogig manually from the geogig.org documents,maybe I don't have to 'node postinstall.js'?

**Comment by jlanio** [comment]
If you have installed Geogig it will still run 'node postinstall.js'.
Geogig-desktop need to know the directory where is geogig command line.

'Node postinstall.js' is used to download geogig command line in Geogig-Desktop/app/static/geogig.
(Among other actions)

**Comment by jlanio** [comment]
I consider the question as closed
